vich_uploader:
    db_driver: orm

    mappings:
        places_image:
            uri_prefix: /img/places
            upload_destination: '%kernel.project_dir%/public/img/places'

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
